# Starter pipeline
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

steps:
- script: npm install
  displayName: 'Install Node.js dependencies'

- script: npm run lint
  displayName: 'Run lint checks'

  - script: npm run build
  displayName: 'Build the project'

- script: npm test
  displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist' # Replace 'dist' with your build output directory
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

  - task: SonarQubePrepare@5
  inputs:
    SonarQube: 'YourSonarQubeServiceConnection'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'your-project-key'
    cliProjectName: 'your-project-name'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

  - task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'YourAzureSubscription'
    appType: 'webApp'
    WebAppName: 'YourWebAppName'
    packageForLinux: '$(System.DefaultWorkingDirectory)/drop/*.zip'
